function [dydt] = SCIB2(t , y , omega_s , theta_s , gamma , eta , Vdc_n , i_dc_r , kappa , G_dc , mu , C_dc , R , L , G , C , V_m)
denom = sqrt( 2 * ( 1 + cos( y(1) ) * cos( theta_s ) + sin( y(1) ) * sin( theta_s ) ) );
nom= cos( theta_s ) * sin( y(1) ) - sin( theta_s ) * cos( y(1) );
u_sw= - nom/denom; % switching angle feedback

dydt = [gamma * u_sw + eta * ( y(2) - Vdc_n ); 
( i_dc_r - kappa * ( y(2) - Vdc_n ) - G_dc * y(2) - mu * ( cos( y(1) ) * y(3) +  sin( y(1) ) * y(4) ) ) / C_dc ; ...
( cos( y(1) ) * y(2) - R * y(3) + L * omega_s * y(4) - y(5) ) / L ; ...
( sin( y(1) ) * y(2) - R * y(4) -  L * omega_s * y(3)  - y(6) ) / L ; ...
( y(3) - G * y(5) + C * omega_s * y(6) - y(7) ) / C ; ...
( y(4) - G * y(6) - C * omega_s * y(5) - y(8) ) / C ; ...
( y(5) - R * y(7) + L * omega_s * y(8) - V_m ) / L ; ...
( y(6) - R * y(8) -  L * omega_s * y(7) ) / L ];
end